(()=>{"use strict";
 const state=GAStorage.load();let mode="simple",pending={};
 const $=id=>document.getElementById(id);
 function save(){GAStorage.save(state)}
 function navigate(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("#tabs button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));scrollTo(0,0)}
 function isSpecial(d){return d.rubric!=="Labor"&&d.rubric!=="Sonstige"&&d.specialty!=="Noch nicht zugeordnet"}
 function abnormal(v){return (v.min!=null&&v.value<v.min)||(v.max!=null&&v.value>v.max)}
 function integrateLabs(doc){let n=0;for(const v of doc.labValues||[]){if(!state.values.some(x=>x.name===v.name&&x.date===v.date&&x.value===v.value)){state.values.push(v);n++}}return n}
 function duplicate(doc){return state.documents.find(d=>(doc.hash&&d.hash===doc.hash)||(d.name===doc.name&&d.date===doc.date))}
 async function saveDoc(id,asCopy=false){let doc=pending[id];if(!doc)return;const dup=duplicate(doc);if(dup&&!asCopy)return GAUI.toast("Dokument ist bereits vorhanden. Bitte Ersetzen oder als Kopie speichern.","error");if(asCopy)doc={...doc,id:GAExtract.uid(),name:doc.name+" (Kopie)"};state.documents.push(doc);const n=$("takeLabs").checked?integrateLabs(doc):0;if($("saveOriginal").checked&&doc._files?.[0])try{await GAStorage.putOriginal(doc.id,doc._files[0])}catch{}delete doc._files;delete pending[id];save();render();GAUI.toast(`Befund gespeichert. ${n} neue Laborwerte übernommen.`)}
 async function replaceDoc(pid,did){const doc=pending[pid],i=state.documents.findIndex(x=>x.id===did);if(!doc||i<0)return;doc.id=did;state.documents[i]=doc;integrateLabs(doc);delete doc._files;delete pending[pid];save();render();GAUI.toast("Vorhandener Befund ersetzt.")}
 function preview(doc){pending[doc.id]=doc;const dup=duplicate(doc);return `<div class="item"><h3>${GAUI.esc(doc.name)}</h3><div class="meta">${GAUI.date(doc.date)} · ${GAUI.esc(doc.type)} · ${GAUI.esc(doc.specialty)}</div>${GAUI.specialHtml(doc.specialtyData)}<pre class="output">${GAUI.esc(GAUI.analysis(doc,"simple"))}</pre>${dup?`<div class="duplicate"><b>Wahrscheinlich bereits vorhanden:</b> ${GAUI.esc(dup.name)}<div class="actions"><button onclick="GAApp.replace('${doc.id}','${dup.id}')">Ersetzen</button><button onclick="GAApp.saveDoc('${doc.id}',true)">Als Kopie</button><button onclick="GAApp.discard('${doc.id}')">Verwerfen</button></div></div>`:`<div class="actions"><button class="primary" onclick="GAApp.saveDoc('${doc.id}')">Befund speichern</button><button onclick="GAApp.discard('${doc.id}')">Verwerfen</button></div>`}</div>`}
 function render(){
  $("metricDocuments").textContent=state.documents.length;$("metricLabs").textContent=state.values.length;$("metricSpecialties").textContent=state.documents.filter(isSpecial).length;$("metricAbnormal").textContent=state.values.filter(abnormal).length;
  $("dashboardSummary").innerHTML=`<p><b>${state.documents.length}</b> Dokumente und <b>${state.values.length}</b> Laborwerte sind lokal gespeichert.</p>`;
  const recent=[...state.documents].sort((a,b)=>(b.date||"").localeCompare(a.date||"")).slice(0,5);$("recentItems").innerHTML=recent.map(d=>`<div class="item"><b>${GAUI.date(d.date)} · ${GAUI.esc(d.name)}</b><div class="small">${GAUI.esc(d.specialty)}</div></div>`).join("")||"<p>Noch keine Einträge.</p>";
  renderDocuments();renderSpecialties();renderLabs();renderTimeline();renderAnalysisSelect();
 }
 function renderDocuments(){
  const q=$("documentSearch").value.toLowerCase(),f=$("documentFilter").value,rubs=[...new Set(state.documents.map(d=>d.rubric))].sort(),cur=f;$("documentFilter").innerHTML='<option value="all">Alle Rubriken</option>'+rubs.map(x=>`<option>${GAUI.esc(x)}</option>`).join("");if(rubs.includes(cur))$("documentFilter").value=cur;
  const arr=[...state.documents].filter(d=>(f==="all"||d.rubric===f)&&`${d.name} ${d.text} ${d.specialty}`.toLowerCase().includes(q)).sort((a,b)=>(b.date||"").localeCompare(a.date||""));
  $("documentList").innerHTML=arr.map(d=>`<div class="item"><h3>${GAUI.esc(d.name)}</h3><div class="meta">${GAUI.date(d.date)} · ${GAUI.esc(d.rubric)} · ${GAUI.esc(d.specialty)}</div>${GAUI.specialHtml(d.specialtyData)}<details><summary>Verständliche Auswertung</summary><pre class="output">${GAUI.esc(GAUI.analysis(d,mode))}</pre></details><div class="actions"><button onclick="GAApp.analyse('${d.id}')">Analysieren</button><button onclick="GAApp.share('${d.id}')">Teilen</button><button onclick="GAApp.remove('${d.id}')">Nur Dokument entfernen</button></div></div>`).join("")||"<article class='card'>Keine Dokumente gefunden.</article>";
 }
 function renderSpecialties(){
  const q=$("specialtySearch").value.toLowerCase(),f=$("specialtyFilter").value,docs=state.documents.filter(isSpecial),specs=[...new Set(docs.map(d=>d.specialty))].sort(),cur=f;$("specialtyFilter").innerHTML='<option value="all">Alle Fachgebiete</option>'+specs.map(x=>`<option>${GAUI.esc(x)}</option>`).join("");if(specs.includes(cur))$("specialtyFilter").value=cur;
  const arr=docs.filter(d=>(f==="all"||d.specialty===f)&&`${d.name} ${d.text} ${JSON.stringify(d.specialtyData)}`.toLowerCase().includes(q)).sort((a,b)=>(b.date||"").localeCompare(a.date||""));
  $("specialtyList").innerHTML=arr.map(d=>`<div class="item"><h3>${GAUI.esc(d.name)}</h3><div class="meta">${GAUI.date(d.date)} · ${GAUI.esc(d.specialty)}</div>${GAUI.specialHtml(d.specialtyData)}${assignBox(d.id)}</div>`).join("")||"<article class='card'>Noch keine Fachbefunde. Neu auswerten oder manuell zuordnen.</article>";
 }
 function assignBox(id){return `<div class="actions"><select id="assign-${id}"><option value="">Fachgebiet ändern …</option><option>Augenheilkunde</option><option>Augenoptik</option><option>Zahnmedizin</option><option>Orthopädie / Unfallchirurgie</option><option>Neurologie</option><option>Urologie</option><option>Kardiologie</option><option>Radiologie</option><option>Hals-Nasen-Ohrenheilkunde</option><option>Allgemeinmedizin</option></select><button onclick="GAApp.assign('${id}')">Zuordnen</button></div>`}
 function renderUnassigned(){const arr=state.documents.filter(d=>!isSpecial(d));$("unassignedList").innerHTML=`<article class="card"><h2>Nicht zugeordnet</h2>${arr.map(d=>`<div class="item"><b>${GAUI.esc(d.name)}</b><div class="small">${GAUI.date(d.date)} · ${GAUI.esc(d.rubric)}</div>${assignBox(d.id)}</div>`).join("")||"<p>Alle Dokumente zugeordnet.</p>"}</article>`}
 function renderLabs(){
  const q=$("labSearch").value.toLowerCase(),f=$("labNameFilter").value,names=[...new Set(state.values.map(v=>v.name))].sort(),cur=f;$("labNameFilter").innerHTML='<option value="all">Alle Werte</option>'+names.map(x=>`<option>${GAUI.esc(x)}</option>`).join("");if(names.includes(cur))$("labNameFilter").value=cur;
  const arr=[...state.values].filter(v=>(f==="all"||v.name===f)&&v.name.toLowerCase().includes(q)).sort((a,b)=>(b.date||"").localeCompare(a.date||""));
  $("labList").innerHTML=arr.map(v=>`<div class="item"><b>${GAUI.esc(v.name)}: ${v.value} ${GAUI.esc(v.unit)}</b><div class="small">${GAUI.date(v.date)}</div></div>`).join("")||"<article class='card'>Keine Laborwerte.</article>";
  const current=$("trendSelect").value;$("trendSelect").innerHTML=names.map(x=>`<option>${GAUI.esc(x)}</option>`).join("");if(names.includes(current))$("trendSelect").value=current;drawTrend()
 }
 function drawTrend(){const name=$("trendSelect").value,arr=state.values.filter(v=>v.name===name).sort((a,b)=>(a.date||"").localeCompare(b.date||"")),c=$("trendCanvas"),ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);if(!arr.length)return;const vals=arr.map(x=>Number(x.value)),min=Math.min(...vals),max=Math.max(...vals),pad=40,range=max-min||1;ctx.beginPath();ctx.lineWidth=3;arr.forEach((v,i)=>{const x=pad+i*(c.width-2*pad)/Math.max(1,arr.length-1),y=c.height-pad-(v.value-min)*(c.height-2*pad)/range;i?ctx.lineTo(x,y):ctx.moveTo(x,y);ctx.fillText(GAUI.date(v.date),x-25,c.height-12);ctx.fillText(String(v.value),x-10,y-8)});ctx.stroke();$("trendText").textContent=`${arr.length} Messung(en) von ${GAUI.date(arr[0].date)} bis ${GAUI.date(arr.at(-1).date)}.`}
 function renderTimeline(){const items=[...state.documents.map(d=>({date:d.date,title:d.name,type:d.specialty})),...state.values.map(v=>({date:v.date,title:`${v.name}: ${v.value} ${v.unit}`,type:"Labor"}))].sort((a,b)=>(b.date||"").localeCompare(a.date||""));$("timelineList").innerHTML=items.map(x=>`<div class="item"><b>${GAUI.date(x.date)} · ${GAUI.esc(x.title)}</b><div class="small">${GAUI.esc(x.type)}</div></div>`).join("")||"<article class='card'>Noch keine Chronik.</article>"}
 function renderAnalysisSelect(){const cur=$("analysisDocument").value;$("analysisDocument").innerHTML='<option value="">Befund auswählen …</option>'+state.documents.map(d=>`<option value="${d.id}">${GAUI.date(d.date)} · ${GAUI.esc(d.name)}</option>`).join("");$("analysisDocument").value=cur}
 async function share(id){const d=state.documents.find(x=>x.id===id),text=GAUI.analysis(d,mode),file=new File([text],`Gesundheitsakte_${d.date}.txt`,{type:"text/plain"});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))await navigator.share({title:d.name,files:[file]});else download(file)}
 function download(blob,name=blob.name||"download"){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 function selfTest(){const funcs=[GAStorage.load,GAExtract.document,GAImporter.process,GAUI.analysis,render],ids=["tabs","fileInput","documentList","specialtyList","labList","timelineList","analysisOutput"];const missing=ids.filter(id=>!$(id));$("selfTest").innerHTML=missing.length?`<p class="status">Fehlende Bereiche: ${missing.join(", ")}</p>`:`<p class="status">Selbsttest erfolgreich: Speicher, Import, Analyse und Ansichten sind geladen.</p>`}
 function wire(){
  $("tabs").onclick=e=>{const b=e.target.closest("button[data-page]");if(b)navigate(b.dataset.page)};
  $("fileInput").onchange=async e=>{const files=[...e.target.files];if(!files.length)return;const docs=await GAImporter.process(files,document.querySelector('input[name="bundleMode"]:checked').value==="bundle");$("importResults").innerHTML=docs.map(preview).join("")||"<p>Keine Vorschau erzeugt.</p>";e.target.value=""};
  $("manualAnalyse").onclick=()=>{const t=$("manualText").value.trim();if(!t)return GAUI.toast("Bitte Text einfügen.","error");const d=GAExtract.document(t,"Manuell eingefügter Befund","text/plain");$("importResults").innerHTML=preview(d)};
  ["documentSearch","documentFilter"].forEach(id=>$(id).oninput=renderDocuments);["specialtySearch","specialtyFilter"].forEach(id=>$(id).oninput=renderSpecialties);["labSearch","labNameFilter"].forEach(id=>$(id).oninput=renderLabs);$("trendSelect").onchange=drawTrend;
  $("reanalyseAll").onclick=()=>{state.documents.forEach(GAExtract.reanalyse);save();render();GAUI.toast("Alle Befunde wurden neu ausgewertet.")};$("showUnassigned").onclick=renderUnassigned;
  $("analysisModes").onclick=e=>{const b=e.target.closest("button[data-mode]");if(!b)return;mode=b.dataset.mode;document.querySelectorAll("#analysisModes button").forEach(x=>x.classList.toggle("active",x===b));renderDocuments()};
  $("runAnalysis").onclick=()=>{const d=state.documents.find(x=>x.id===$("analysisDocument").value);$("analysisOutput").textContent=d?GAUI.analysis(d,mode):"Bitte Befund auswählen."};
  $("assistantRun").onclick=()=>{const q=$("assistantQuestion").value.toLowerCase();let arr=state.documents.filter(d=>`${d.name} ${d.text} ${d.specialty}`.toLowerCase().includes(q.split(/\s+/).find(x=>x.length>3)||q));if(/auge|brille|visus/.test(q))arr=state.documents.filter(d=>/Auge|Optik/.test(d.specialty));$("assistantOutput").textContent=arr.map(d=>`${GAUI.date(d.date)} · ${d.name}\n${d.keyStatements?.slice(0,3).join(" | ")}`).join("\n\n")||"Keine eindeutigen Treffer."};
  $("downloadBackup").onclick=()=>{const data=GAStorage.backup(state);download(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),`Gesundheitsakte_Backup_${new Date().toISOString().slice(0,10)}.json`);$("backupInfo").textContent="Sicherung wurde zum Download bereitgestellt."};
  $("shareBackup").onclick=async()=>{const data=GAStorage.backup(state),f=new File([JSON.stringify(data,null,2)],`Gesundheitsakte_Backup_${new Date().toISOString().slice(0,10)}.json`,{type:"application/json"});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[f]})))await navigator.share({title:"Gesundheitsakte Sicherung",files:[f]});else download(f);$("backupInfo").textContent="Teilen beziehungsweise Download wurde geöffnet."};
  $("restoreBackup").onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(confirm("Diese Sicherung wiederherstellen?")){Object.assign(state,GAStorage.restore(data));render();GAUI.toast("Sicherung wiederhergestellt.")}}catch(err){GAUI.toast("Sicherung ungültig: "+err.message,"error")}e.target.value=""};
  $("forceUpdate").onclick=async()=>{if("serviceWorker"in navigator)(await navigator.serviceWorker.getRegistrations()).forEach(r=>r.unregister());if("caches"in window)(await caches.keys()).forEach(k=>caches.delete(k));location.reload()};
 }
 window.GAApp={saveDoc,replace:replaceDoc,discard:id=>{delete pending[id];$("importResults").innerHTML="";GAUI.toast("Import verworfen.")},analyse:id=>{navigate("analysis");$("analysisDocument").value=id;$("runAnalysis").click()},share,remove:id=>{if(confirm("Nur das Dokument entfernen? Bereits übernommene Laborwerte bleiben erhalten.")){state.documents=state.documents.filter(x=>x.id!==id);save();render()}},assign:id=>{const d=state.documents.find(x=>x.id===id),v=$(`assign-${id}`).value;if(!d||!v)return;d.specialty=v;d.rubric=v==="Augenoptik"?"Optik / Brille":v==="Zahnmedizin"?"Zahnmedizin":v.split(" / ")[0];GAExtract.reanalyse(d);save();render();GAUI.toast("Fachgebiet zugeordnet.")}};
 window.addEventListener("error",e=>GAUI.toast(`Programmfehler: ${e.message}`,"error"));window.addEventListener("unhandledrejection",e=>GAUI.toast(`Importfehler: ${e.reason?.message||e.reason}`,"error"));
 wire();state.documents.forEach(GAExtract.reanalyse);save();render();selfTest();GAUI.toast("Gesundheitsakte 3.0 wurde vollständig geladen.");
 if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js?v=3.0.0",{updateViaCache:"none"}).catch(console.warn);
})();